name: test job
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  job2:
    runs-on: ubuntu-latest
    needs: job1 # job1인 완성되어야 job2를 실행
    steps:
      - run: echo ${{ github.job }}
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2] # job1과 job2가 완성되어야 job3를 실행
    steps:
      - run: echo ${{ github.job }}