name: Our Steps
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      - run: echo $GIHUB_STATE
      - name: Save output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT