name: our steps
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - id: no-condition-failure
        run: exit 1
      - if: ${{ always() }}
        run: echo ${{ steps.random.outcome }}