name: Our Jobs
on: push
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - window-latest
          - macos-latest
    steps:
      - run: date