name: Our Jobs
on: push
jobs:
  echo: # 첫 번째 작업 echo는 무조건 실행이 되며
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello!'
  echo_if: # 두 번째 작업은 push 이벤트가 main 브랜치에에서 발생 했을 경우에만 발생
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - run: echo 'Hello, Main!'
  skip_ci: # 세 번째 작업은 커밋 메시지에 skip ci가 포함되지 않았을 경우에만 실행
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }} 
    steps:
      - run: echo 'Hello, Skip CI!'