name: our steps
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: if [[ $((RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
      - if: ${{ always() }}
        run: echo ${{ steps.random.outcome }}